*------------------------------------------------------------*;
* Computed Code;
*------------------------------------------------------------*;
*------------------------------------------------------------*;
* TRANSFORM: IMP_Age , log(IMP_Age + 1);
*------------------------------------------------------------*;
label LOG_IMP_Age = 'Transformed: Imputed Age';
length LOG_IMP_Age 8;
if IMP_Age eq . then LOG_IMP_Age = .;
else do;
if IMP_Age + 1 > 0 then LOG_IMP_Age = log(IMP_Age + 1);
else LOG_IMP_Age = .;
end;
*------------------------------------------------------------*;
* TRANSFORM: Items_Purchased , log(Items_Purchased + 1);
*------------------------------------------------------------*;
label LOG_Items_Purchased = 'Transformed: Items Purchased';
length LOG_Items_Purchased 8;
if Items_Purchased eq . then LOG_Items_Purchased = .;
else do;
if Items_Purchased + 1 > 0 then LOG_Items_Purchased = log(Items_Purchased + 1);
else LOG_Items_Purchased = .;
end;
